const TODO_ACTION_TYPES = {
    ADD_TODO: 'ADD_TODO',
    TOGGLE_TODO: 'TOGGLE_TODO',
    DELETE_TODO: 'DELETE_TODO',
    SHOW_ALL: 'SHOW_ALL',
    SHOW_COMPLETED: 'SHOW_COMPLETED',
    SHOW_ACTIVE: 'SHOW_ACTIVE',
    SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER'
}

export default TODO_ACTION_TYPES;